name: Snes9x GX Build

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        make -j2
    
    - name: Copy files
      run: | 
        cp -f hbc/* executables/Snes9xGX/apps/snes9xgx/
        cp -f hbc/* executables/Snes9xGX-GameCube/
        cp -f README.md executables/Snes9xGX/apps/snes9xgx/
        cp -f README.md executables/Snes9xGX-GameCube/

    - name: Upload Wii Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Snes9xGX-Nightly
        path: |
         executables/Snes9xGX/
         !executables/Snes9xGX/apps/snes9xgx/*.elf
    
    - name: Upload GameCube Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Snes9xGX-Nightly-GameCube
        path: |
         executables/Snes9xGX-GameCube/
         !executables/Snes9xGX-GameCube/*.elf
