name: Snes9x GX Build

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        make -j2
    
    - name: Copy files
      run: | 
        mkdir -p dist/Snes9xGX/apps/snes9xgx
        mkdir -p dist/Snes9xGX/snes9xgx/roms
        mkdir dist/Snes9xGX/snes9xgx/cheats
        mkdir dist/Snes9xGX/snes9xgx/saves
        mkdir dist/Snes9xGX-GameCube/
        cp hbc/* dist/Snes9xGX/apps/snes9xgx/
        cp executables/snes9xgx-wii.dol dist/Snes9xGX/apps/snes9xgx/boot.dol
        cp executables/snes9xgx-gc.dol dist/Snes9xGX-GameCube/
        touch dist/Snes9xGX/snes9xgx/roms/romdir
        touch dist/Snes9xGX/snes9xgx/cheats/cheatsdir
        touch dist/Snes9xGX/snes9xgx/saves/savesdir

    - name: Upload Wii Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Snes9xGX
        path: |
         dist/Snes9xGX/
    
    - name: Upload GameCube Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Snes9xGX-GameCube
        path: |
         dist/Snes9xGX-GameCube/
